//generated by ChatGPT, edited by Isabella Phung for UCSC CSE121 Spring Lab 5
#include <stdio.h>
#include <string.h>
#include <stdbool.h>
#include <stdint.h>

#define high    -1 //raw value boundry for led on
#define sampling_inHz 10*1000 //default is 20kHz
#define dot_length 10 //length of dot in ms
#define time_unit 1
//#define time_unit dot_length*(sampling_inHz/1000)

//char* binaryTree[] = {NULL, "E", "T", "I", "A", "N", "M", "S", "U", "R", "W", "D", "K", "G", "O", "H", "V", "F", NULL, "L", NULL, "P", "J", "B", "X", "C", "Y", "Z", "Q", NULL, NULL, "5", "4", NULL, "3", NULL, NULL, NULL, "2", NULL, NULL, "+", NULL, NULL, NULL, NULL, "1", "6", "=", "/", NULL, NULL, NULL, NULL, NULL, "7", NULL, NULL, NULL, "8", NULL, "9", "0"};

int main(int arc, char **argv){
    bool messageStarted = false;
    uint32_t rawData;
    int prev = 2; //holds previous state
    uint32_t counter = 0; //used to keep track of how long we've been getting high Val and how long our pause is
    char message[1024] = "";
    char space[2] = " ";
    int index = 0;
    //char* testMorse = "000011111110000000111000000011100011100011100000001111111000000000";
    char* testMorse = "00001011100000001110001000101010001110000000000";
    char* testMorseCpy = testMorse;
    while(*testMorseCpy){
        rawData = *testMorseCpy - '0';

        if(rawData ==1 && !messageStarted){
            messageStarted = true;
            counter = 0;
            prev = 2;
        } 
        if(messageStarted){
            if(rawData == 1){
                if(prev == 0){ //letter start, check length of pause
                    if(counter > 0 && counter <= time_unit*3 + 1 && counter >= time_unit*3 - 1 ){ //letter end
                        printf("character in binary Tree: %s\n", binaryTree[index]);
                        strcat(message, binaryTree[index]);
                        printf("message: %s\n", message);
                        index = 0;
                    } else if(counter > 0 && counter <= time_unit*7 + 1 && counter >= time_unit*7 - 1 ){  //space
                        strcat(message, binaryTree[index]);
                        strcat(message, space);
                        index = 0;
                    }
                    counter = 0;
                }
                prev = 1;
            }else{
                if(prev == 1){//letter end, check length of letter
                    if(counter <= time_unit + 1){ //it's a dit
                        printf(".\n");
                        index = (index*2)+1; 
                    } else{ //it's a dah
                        printf("-\n");
                        index = (index*2)+2; 
                    }
                    counter = 0;
                }
                if(counter > time_unit*7 + 1){ //if we're at end of message, 
                    strcat(message, binaryTree[index]);
                    messageStarted = false; 
                    printf("%s\n", message);
                }
                prev = 0;
            }
            counter++;
        }
        testMorseCpy++;
    }
    return 0;
}
